# -*- mode:python -*-

Import('*')


shared_flags = [
    '-Wno-format',
    '-Wno-missing-field-initializers',
]
flag_appends = {
    'CCFLAGS': shared_flags,
    'CXXFLAGS': shared_flags,
}

path_appends = {
    'CPPPATH': [
        'cpu/nemu/include',
    'cpu/nemu/src/engine/interpreter',
    'cpu/nemu/resource',
    ]}
def_appends = {
    'CPPDEFINES': {
        '__DIFF_REF_QEMU__': None,
        'XIANGSHAN': 1,
        '_SHARE': 0,

        '__ENGINE_interpreter__': None,
        '__SIMPOINT': None,
        '__GCPT_COMPATIBLE__': None,
        '__ISA__': 'riscv64',
        '__ISA_riscv64__': None,
        '_ISA_H_': '\\"isa/riscv64.h\\"',
    }}
cc_replace = {'CC': 'g++'}

appends = {**path_appends, **def_appends, **flag_appends}


nemu_files = [
    './src/main.c',
    './src/device/vga.c',
    './src/device/alarm.c',
    './src/device/uartlite.c',
    './src/device/intr.c',
    './src/device/device.c',
    './src/device/audio.c',
    './src/device/io/mmio.c',
    './src/device/io/map.c',
    './src/device/io/port-io.c',
    './src/device/sdcard.c',
    './src/device/serial.c',
    './src/device/keyboard.c',
    './src/device/timer.c',
    './src/isa/riscv64/logo.c',
    './src/isa/riscv64/init.c',
    './src/isa/riscv64/exec/exec.c',
    './src/isa/riscv64/exec/special.c',
    './src/isa/riscv64/difftest/ref.c',
    './src/isa/riscv64/difftest/dut.c',
    './src/isa/riscv64/reg.c',
    './src/isa/riscv64/mmu.c',
    './src/isa/riscv64/intr.c',
    './src/isa/riscv64/clint.c',
    './src/monitor/cpu-exec.c',
    './src/monitor/monitor.c',
    './src/monitor/difftest/ref.c',
    './src/monitor/difftest/dut.c',
    './src/monitor/debug/expr.c',
    './src/monitor/debug/ui.c',
    './src/monitor/debug/watchpoint.c',
    './src/monitor/debug/log.c',
    './src/memory/paddr.c',
    './src/memory/vaddr.c',
    './src/engine/interpreter/init.c',
    './src/checkpoint/profiler.cpp',
    './src/checkpoint/serializer.cpp',
    './src/checkpoint/path_manager.cpp',
    './src/checkpoint/simpoint.cpp',
    './src/iostream3/zfstream.cpp',
    './src/base/output.cpp',
    ]

if 'NemuCPU' in env['CPU_MODELS']:
    SimObject('NemuCPU.py')

    Source('cpu.cc')

    for f in nemu_files:
        Source(f, append=appends, replace=cc_replace)
